/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Restitution API
 * API for the Restitution Application
 * OpenAPI spec version: v1
 */
import { HttpClient, HttpHeaders } from '@angular/common/http';
import type { HttpContext, HttpEvent, HttpParams, HttpResponse as AngularHttpResponse } from '@angular/common/http';

import { Injectable, inject } from '@angular/core';

import { Observable } from 'rxjs';

import type { CreateRestitutionCaseRequestDto } from '../../model';

interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?: HttpParams | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: { includeHeaders?: string[] } | boolean;
}

@Injectable({ providedIn: 'root' })
export class RestitutionsService {
  private readonly http = inject(HttpClient);
  postApiRestitutions<TData = void>(
    createRestitutionCaseRequestDto: CreateRestitutionCaseRequestDto,
    options?: HttpClientOptions & { observe?: 'body' }
  ): Observable<TData>;
  postApiRestitutions<TData = void>(
    createRestitutionCaseRequestDto: CreateRestitutionCaseRequestDto,
    options?: HttpClientOptions & { observe: 'events' }
  ): Observable<HttpEvent<TData>>;
  postApiRestitutions<TData = void>(
    createRestitutionCaseRequestDto: CreateRestitutionCaseRequestDto,
    options?: HttpClientOptions & { observe: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
  postApiRestitutions<TData = void>(
    createRestitutionCaseRequestDto: CreateRestitutionCaseRequestDto,
    options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(`/api/Restitutions`, createRestitutionCaseRequestDto, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events'
      });
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(`/api/Restitutions`, createRestitutionCaseRequestDto, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response'
      });
    }

    return this.http.post<TData>(`/api/Restitutions`, createRestitutionCaseRequestDto, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body'
    });
  }
}
