/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Restitution API
 * API for the Restitution Application
 * OpenAPI spec version: v1
 */
import { HttpClient, HttpHeaders } from '@angular/common/http';
import type { HttpContext, HttpEvent, HttpParams, HttpResponse as AngularHttpResponse } from '@angular/common/http';

import { Injectable, inject } from '@angular/core';

import { Observable } from 'rxjs';

import type {
  CreateOffenderRestitutionCaseRequestDto,
  CreateVictimEntityRestitutionCaseRequestDto,
  CreateVictimRestitutionCaseRequestDto
} from '../../model';

interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?: HttpParams | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: { includeHeaders?: string[] } | boolean;
}

@Injectable({ providedIn: 'root' })
export class RestitutionsService {
  private readonly http = inject(HttpClient);
  postApiRestitutionsVictim<TData = void>(
    createVictimRestitutionCaseRequestDto: CreateVictimRestitutionCaseRequestDto,
    options?: HttpClientOptions & { observe?: 'body' }
  ): Observable<TData>;
  postApiRestitutionsVictim<TData = void>(
    createVictimRestitutionCaseRequestDto: CreateVictimRestitutionCaseRequestDto,
    options?: HttpClientOptions & { observe: 'events' }
  ): Observable<HttpEvent<TData>>;
  postApiRestitutionsVictim<TData = void>(
    createVictimRestitutionCaseRequestDto: CreateVictimRestitutionCaseRequestDto,
    options?: HttpClientOptions & { observe: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
  postApiRestitutionsVictim<TData = void>(
    createVictimRestitutionCaseRequestDto: CreateVictimRestitutionCaseRequestDto,
    options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(`/restwebforms/api/restitutions/victim`, createVictimRestitutionCaseRequestDto, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events'
      });
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(`/restwebforms/api/restitutions/victim`, createVictimRestitutionCaseRequestDto, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response'
      });
    }

    return this.http.post<TData>(`/restwebforms/api/restitutions/victim`, createVictimRestitutionCaseRequestDto, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body'
    });
  }
  postApiRestitutionsVictimEntity<TData = void>(
    createVictimEntityRestitutionCaseRequestDto: CreateVictimEntityRestitutionCaseRequestDto,
    options?: HttpClientOptions & { observe?: 'body' }
  ): Observable<TData>;
  postApiRestitutionsVictimEntity<TData = void>(
    createVictimEntityRestitutionCaseRequestDto: CreateVictimEntityRestitutionCaseRequestDto,
    options?: HttpClientOptions & { observe: 'events' }
  ): Observable<HttpEvent<TData>>;
  postApiRestitutionsVictimEntity<TData = void>(
    createVictimEntityRestitutionCaseRequestDto: CreateVictimEntityRestitutionCaseRequestDto,
    options?: HttpClientOptions & { observe: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
  postApiRestitutionsVictimEntity<TData = void>(
    createVictimEntityRestitutionCaseRequestDto: CreateVictimEntityRestitutionCaseRequestDto,
    options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
        `/restwebforms/api/restitutions/victim-entity`,
        createVictimEntityRestitutionCaseRequestDto,
        {
          ...(options as Omit<NonNullable<typeof options>, 'observe'>),
          observe: 'events'
        }
      );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
        `/restwebforms/api/restitutions/victim-entity`,
        createVictimEntityRestitutionCaseRequestDto,
        {
          ...(options as Omit<NonNullable<typeof options>, 'observe'>),
          observe: 'response'
        }
      );
    }

    return this.http.post<TData>(
      `/restwebforms/api/restitutions/victim-entity`,
      createVictimEntityRestitutionCaseRequestDto,
      {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body'
      }
    );
  }
  postApiRestitutionsOffender<TData = void>(
    createOffenderRestitutionCaseRequestDto: CreateOffenderRestitutionCaseRequestDto,
    options?: HttpClientOptions & { observe?: 'body' }
  ): Observable<TData>;
  postApiRestitutionsOffender<TData = void>(
    createOffenderRestitutionCaseRequestDto: CreateOffenderRestitutionCaseRequestDto,
    options?: HttpClientOptions & { observe: 'events' }
  ): Observable<HttpEvent<TData>>;
  postApiRestitutionsOffender<TData = void>(
    createOffenderRestitutionCaseRequestDto: CreateOffenderRestitutionCaseRequestDto,
    options?: HttpClientOptions & { observe: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
  postApiRestitutionsOffender<TData = void>(
    createOffenderRestitutionCaseRequestDto: CreateOffenderRestitutionCaseRequestDto,
    options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(`/restwebforms/api/restitutions/offender`, createOffenderRestitutionCaseRequestDto, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events'
      });
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(`/restwebforms/api/restitutions/offender`, createOffenderRestitutionCaseRequestDto, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response'
      });
    }

    return this.http.post<TData>(`/restwebforms/api/restitutions/offender`, createOffenderRestitutionCaseRequestDto, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body'
    });
  }
}
