/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Restitution API
 * API for the Restitution Application
 * OpenAPI spec version: v1
 */

export interface ApplicationDto {
  applicantType?: number;
  /** @nullable */
  applicantsFirstName?: string | null;
  /** @nullable */
  applicantsMiddleName?: string | null;
  /** @nullable */
  applicantsLastName?: string | null;
  /** @nullable */
  otherFirstName?: string | null;
  /** @nullable */
  otherLastName?: string | null;
  /** @nullable */
  applicantsGenderCode?: number | null;
  /** @nullable */
  applicantsBirthDate?: string | null;
  /** @nullable */
  indigenous?: number | null;
  /** @nullable */
  applicantsPreferredMethodOfContact?: number | null;
  /** @nullable */
  smsPreferred?: number | null;
  /** @nullable */
  applicantsPrimaryPhoneNumber?: string | null;
  /** @nullable */
  applicantsAlternatePhoneNumber?: string | null;
  /** @nullable */
  applicantsEmail?: string | null;
  /** @nullable */
  applicantsPrimaryAddressLine1?: string | null;
  /** @nullable */
  applicantsPrimaryAddressLine2?: string | null;
  /** @nullable */
  applicantsPrimaryAddressLine3?: string | null;
  /** @nullable */
  applicantsPrimaryCity?: string | null;
  /** @nullable */
  applicantsPrimaryProvince?: string | null;
  /** @nullable */
  applicantsPrimaryPostalCode?: string | null;
  /** @nullable */
  applicantsPrimaryCountry?: string | null;
  /** @nullable */
  offenderFirstName?: string | null;
  /** @nullable */
  offenderMiddleName?: string | null;
  /** @nullable */
  offenderLastName?: string | null;
  /** @nullable */
  voicemailOption?: number | null;
  /** @nullable */
  applicantsSignature?: string | null;
  /** @nullable */
  declarationFullName?: string | null;
  /** @nullable */
  signingOfficerTitle?: string | null;
  /** @nullable */
  declarationDate?: string | null;
  /** @nullable */
  contactTitle?: string | null;
  /** @nullable */
  offenderCustodyLocation?: string | null;
  /** @nullable */
  genderIdentityText?: string | null;
  /** @nullable */
  primaryRaceEthnicity?: number | null;
  /** @nullable */
  primaryRaceEthnicityText?: string | null;
  /** @nullable */
  pronouns?: number | null;
  /** @nullable */
  pronounsText?: string | null;
}
