/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Restitution API
 * API for the Restitution Application
 * OpenAPI spec version: v1
 */

export interface ApplicationDto {
  applicantType?: number;
  /** @minLength 1 */
  applicantsFirstName: string;
  /** @nullable */
  applicantsMiddleName?: string | null;
  /** @minLength 1 */
  applicantsLastName: string;
  /** @nullable */
  otherFirstName?: string | null;
  /** @nullable */
  otherLastName?: string | null;
  /** @nullable */
  applicantsGenderCode?: number | null;
  applicantsBirthDate: string;
  /** @nullable */
  indigenous?: number | null;
  applicantsPreferredMethodOfContact: number;
  /** @nullable */
  smsPreferred?: number | null;
  /** @nullable */
  applicantsPrimaryPhoneNumber?: string | null;
  /** @nullable */
  applicantsAlternatePhoneNumber?: string | null;
  /** @nullable */
  applicantsEmail?: string | null;
  /** @minLength 1 */
  applicantsPrimaryAddressLine1: string;
  /** @nullable */
  applicantsPrimaryAddressLine2?: string | null;
  /** @nullable */
  applicantsPrimaryAddressLine3?: string | null;
  /** @minLength 1 */
  applicantsPrimaryCity: string;
  /** @minLength 1 */
  applicantsPrimaryProvince: string;
  /** @minLength 1 */
  applicantsPrimaryPostalCode: string;
  /** @minLength 1 */
  applicantsPrimaryCountry: string;
  /** @nullable */
  offenderFirstName?: string | null;
  /** @nullable */
  offenderMiddleName?: string | null;
  /** @nullable */
  offenderLastName?: string | null;
  /** @nullable */
  voicemailOption?: number | null;
  /** @minLength 1 */
  applicantsSignature: string;
  /** @nullable */
  declarationFullName?: string | null;
  /** @nullable */
  signingOfficerTitle?: string | null;
  /** @nullable */
  declarationDate?: string | null;
  /** @nullable */
  contactTitle?: string | null;
  /** @nullable */
  offenderCustodyLocation?: string | null;
  /** @nullable */
  genderIdentityText?: string | null;
  /** @nullable */
  primaryRaceEthnicity?: number | null;
  /** @nullable */
  primaryRaceEthnicityText?: string | null;
  /** @nullable */
  pronouns?: number | null;
  /** @nullable */
  pronounsText?: string | null;
}
