/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Restitution API
 * API for the Restitution Application
 * OpenAPI spec version: v1
 */

export interface ApplicationDto {
  applicanttype?: number;
  /** @nullable */
  applicantsfirstname?: string | null;
  /** @nullable */
  applicantsmiddlename?: string | null;
  /** @nullable */
  applicantslastname?: string | null;
  /** @nullable */
  otherfirstname?: string | null;
  /** @nullable */
  otherlastname?: string | null;
  /** @nullable */
  applicantsgendercode?: number | null;
  /** @nullable */
  applicantsbirthdate?: string | null;
  /** @nullable */
  indigenous?: number | null;
  /** @nullable */
  applicantspreferredmethodofcontact?: number | null;
  /** @nullable */
  smspreferred?: number | null;
  /** @nullable */
  applicantsprimaryphonenumber?: string | null;
  /** @nullable */
  applicantsalternatephonenumber?: string | null;
  /** @nullable */
  applicantsemail?: string | null;
  /** @nullable */
  applicantsprimaryaddressline1?: string | null;
  /** @nullable */
  applicantsprimaryaddressline2?: string | null;
  /** @nullable */
  applicantsprimaryaddressline3?: string | null;
  /** @nullable */
  applicantsprimarycity?: string | null;
  /** @nullable */
  applicantsprimaryprovince?: string | null;
  /** @nullable */
  applicantsprimarypostalcode?: string | null;
  /** @nullable */
  applicantsprimarycountry?: string | null;
  /** @nullable */
  offenderfirstname?: string | null;
  /** @nullable */
  offendermiddlename?: string | null;
  /** @nullable */
  offenderlastname?: string | null;
  /** @nullable */
  voicemailoption?: number | null;
  /** @nullable */
  applicantssignature?: string | null;
  /** @nullable */
  declarationfullname?: string | null;
  /** @nullable */
  signingofficertitle?: string | null;
  /** @nullable */
  declarationdate?: string | null;
  /** @nullable */
  contacttitle?: string | null;
  /** @nullable */
  offendercustodylocation?: string | null;
  /** @nullable */
  genderidentitytext?: string | null;
  /** @nullable */
  primaryraceethnicity?: number | null;
  /** @nullable */
  primaryraceethnicitytext?: string | null;
  /** @nullable */
  pronouns?: number | null;
  /** @nullable */
  pronountext?: string | null;
}
