/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Restitution API
 * API for the Restitution Application
 * OpenAPI spec version: v1
 */
import type { CityLookupDto } from './cityLookupDto';

export interface CityLookupDtoLookupResponseDto {
  /** @nullable */
  value?: CityLookupDto[] | null;
}
