/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * Restitution API
 * API for the Restitution Application
 * OpenAPI spec version: v1
 */
import type { CityLookupDto } from './cityLookupDto';
import type { CountryLookupDto } from './countryLookupDto';
import type { ProvinceLookupDto } from './provinceLookupDto';

export interface CitySearchResponseDto {
  /** @nullable */
  result?: string | null;
  /** @nullable */
  cityCollection?: CityLookupDto[] | null;
  /** @nullable */
  countryCollection?: CountryLookupDto[] | null;
  /** @nullable */
  provinceCollection?: ProvinceLookupDto[] | null;
}
