/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Restitution API
 * API for the Restitution Application
 * OpenAPI spec version: v1
 */

export interface CourtInfo {
  /** @nullable */
  readonly fortunecookietype?: string | null;
  /** @nullable */
  vsd_courtfilenumber?: string | null;
  /** @nullable */
  vsd_courtlocation?: string | null;
}
