/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Restitution API
 * API for the Restitution Application
 * OpenAPI spec version: v1
 */

export interface DocumentCollection {
  /** @nullable */
  readonly fortunecookietype?: string | null;
  /** @nullable */
  filename?: string | null;
  /** @nullable */
  body?: string | null;
  /** @nullable */
  subject?: string | null;
}
