/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Restitution API
 * API for the Restitution Application
 * OpenAPI spec version: v1
 */

export interface DocumentDto {
  /** @nullable */
  filename?: string | null;
  /** @nullable */
  body?: string | null;
  /** @nullable */
  subject?: string | null;
}
