/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Restitution API
 * API for the Restitution Application
 * OpenAPI spec version: v1
 */

export type GetApiLookupCitiesSearchParams = {
  country?: string;
  province?: string;
  searchVal?: string;
  limit?: number;
};
