/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * Restitution API
 * API for the Restitution Application
 * OpenAPI spec version: v1
 */
import type { LookupItemDto } from './lookupItemDto';

export interface LookupItemDtoLookupResponseDto {
  /** @nullable */
  value?: LookupItemDto[] | null;
}
