/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Restitution API
 * API for the Restitution Application
 * OpenAPI spec version: v1
 */

export interface LookupItemDto {
  /** @nullable */
  id?: string | null;
  /** @nullable */
  name?: string | null;
}
