/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Restitution API
 * API for the Restitution Application
 * OpenAPI spec version: v1
 */

export interface Participant {
  /** @nullable */
  readonly fortunecookietype?: string | null;
  /** @nullable */
  vsd_firstname?: string | null;
  /** @nullable */
  vsd_middlename?: string | null;
  /** @nullable */
  vsd_lastname?: string | null;
  /** @nullable */
  vsd_preferredname?: string | null;
  /** @nullable */
  vsd_companyname?: string | null;
  /** @nullable */
  vsd_name?: string | null;
  /** @nullable */
  vsd_addressline1?: string | null;
  /** @nullable */
  vsd_addressline2?: string | null;
  /** @nullable */
  vsd_addressline3?: string | null;
  /** @nullable */
  vsd_city?: string | null;
  /** @nullable */
  vsd_province?: string | null;
  /** @nullable */
  vsd_country?: string | null;
  /** @nullable */
  vsd_postalcode?: string | null;
  /** @nullable */
  vsd_preferredmethodofcontact?: number | null;
  /** @nullable */
  vsd_restcontactpreferenceforupdates?: number | null;
  /** @nullable */
  vsd_phonenumber?: string | null;
  /** @nullable */
  vsd_alternatephonenumber?: string | null;
  /** @nullable */
  vsd_voicemailoptions?: number | null;
  /** @nullable */
  vsd_email?: string | null;
  /** @nullable */
  vsd_rest_custodylocation?: string | null;
  /** @nullable */
  vsd_rest_programname?: string | null;
  /** @nullable */
  vsd_relationship1?: string | null;
  /** @nullable */
  vsd_relationship2?: string | null;
  /** @nullable */
  vsd_relationship2other?: string | null;
  /** @nullable */
  vsd_title?: string | null;
  /** @nullable */
  vsd_contacttitle?: string | null;
  /** @nullable */
  vsd_smspreferred?: number | null;
  /** @nullable */
  vsd_isprimaryentitycontact?: number | null;
}
