/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * Restitution API
 * API for the Restitution Application
 * OpenAPI spec version: v1
 */

export interface ProvinceLookupDto {
  /** @nullable */
  vsd_code?: string | null;
  /** @nullable */
  _vsd_countryid_value?: string | null;
  /** @nullable */
  vsd_name?: string | null;
  /** @nullable */
  vsd_provinceid?: string | null;
}
