/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Restitution API
 * API for the Restitution Application
 * OpenAPI spec version: v1
 */
import type { ProvinceLookupDto } from './provinceLookupDto';

export interface ProvinceLookupDtoLookupResponseDto {
  /** @nullable */
  value?: ProvinceLookupDto[] | null;
}
