/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * Restitution API
 * API for the Restitution Application
 * OpenAPI spec version: v1
 */

export interface RelationshipLookupDto {
  /** @nullable */
  vsd_name?: string | null;
  /** @nullable */
  vsd_relationshipid?: string | null;
}
