/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Restitution API
 * API for the Restitution Application
 * OpenAPI spec version: v1
 */

export interface RestitutionApplication {
  /** @nullable */
  readonly fortunecookietype?: string | null;
  vsd_applicanttype?: number;
  /** @nullable */
  vsd_applicantsfirstname?: string | null;
  /** @nullable */
  vsd_applicantsmiddlename?: string | null;
  /** @nullable */
  vsd_applicantslastname?: string | null;
  /** @nullable */
  vsd_otherfirstname?: string | null;
  /** @nullable */
  vsd_otherlastname?: string | null;
  /** @nullable */
  vsd_applicantsgendercode?: number | null;
  /** @nullable */
  vsd_applicantsbirthdate?: string | null;
  /** @nullable */
  vsd_indigenous?: number | null;
  /** @nullable */
  vsd_applicantspreferredmethodofcontact?: number | null;
  /** @nullable */
  vsd_smspreferred?: number | null;
  /** @nullable */
  vsd_applicantsprimaryphonenumber?: string | null;
  /** @nullable */
  vsd_applicantsalternatephonenumber?: string | null;
  /** @nullable */
  vsd_applicantsemail?: string | null;
  /** @nullable */
  vsd_applicantsprimaryaddressline1?: string | null;
  /** @nullable */
  vsd_applicantsprimaryaddressline2?: string | null;
  /** @nullable */
  vsd_applicantsprimaryaddressline3?: string | null;
  /** @nullable */
  vsd_applicantsprimarycity?: string | null;
  /** @nullable */
  vsd_applicantsprimaryprovince?: string | null;
  /** @nullable */
  vsd_applicantsprimarypostalcode?: string | null;
  /** @nullable */
  vsd_applicantsprimarycountry?: string | null;
  /** @nullable */
  vsd_cvap_offenderfirstname?: string | null;
  /** @nullable */
  vsd_cvap_offendermiddlename?: string | null;
  /** @nullable */
  vsd_cvap_offenderlastname?: string | null;
  /** @nullable */
  vsd_voicemailoption?: number | null;
  /** @nullable */
  vsd_applicantssignature?: string | null;
  /** @nullable */
  vsd_declarationfullname?: string | null;
  /** @nullable */
  vsd_signingofficertitle?: string | null;
  /** @nullable */
  vsd_declarationdate?: string | null;
  /** @nullable */
  vsd_contacttitle?: string | null;
  /** @nullable */
  vsd_offendercustodylocation?: string | null;
  /** @nullable */
  vsd_genderidentitytext?: string | null;
  /** @nullable */
  vsd_primaryraceethnicity?: number | null;
  /** @nullable */
  vsd_primaryraceethnicitytext?: string | null;
  /** @nullable */
  vsd_pronouns?: number | null;
  /** @nullable */
  vsd_pronountext?: string | null;
}
