/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Restitution API
 * API for the Restitution Application
 * OpenAPI spec version: v1
 */
import type { CourtInfo } from './courtInfo';
import type { DocumentCollection } from './documentCollection';
import type { Participant } from './participant';
import type { RestitutionApplication } from './restitutionApplication';

export interface RestitutionFormModel {
  application?: RestitutionApplication;
  /** @nullable */
  courtInfoCollection?: CourtInfo[] | null;
  /** @nullable */
  providerCollection?: Participant[] | null;
  /** @nullable */
  documentCollection?: DocumentCollection[] | null;
}
