/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Restitution API
 * API for the Restitution Application
 * OpenAPI spec version: v1
 */
import { HttpClient, HttpHeaders } from '@angular/common/http';
import type { HttpContext, HttpEvent, HttpParams, HttpResponse as AngularHttpResponse } from '@angular/common/http';

import { Injectable, inject } from '@angular/core';

import { Observable } from 'rxjs';

import type { GetApiLookupCitiesSearchParams } from '../../model';

interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?: HttpParams | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: { includeHeaders?: string[] } | boolean;
}

@Injectable({ providedIn: 'root' })
export class LookupService {
  private readonly http = inject(HttpClient);
  getApiLookupCountries<TData = void>(options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
  getApiLookupCountries<TData = void>(
    options?: HttpClientOptions & { observe: 'events' }
  ): Observable<HttpEvent<TData>>;
  getApiLookupCountries<TData = void>(
    options?: HttpClientOptions & { observe: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
  getApiLookupCountries<TData = void>(
    options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(`/api/Lookup/countries`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events'
      });
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(`/api/Lookup/countries`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response'
      });
    }

    return this.http.get<TData>(`/api/Lookup/countries`, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body'
    });
  }
  getApiLookupProvinces<TData = void>(options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
  getApiLookupProvinces<TData = void>(
    options?: HttpClientOptions & { observe: 'events' }
  ): Observable<HttpEvent<TData>>;
  getApiLookupProvinces<TData = void>(
    options?: HttpClientOptions & { observe: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
  getApiLookupProvinces<TData = void>(
    options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(`/api/Lookup/provinces`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events'
      });
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(`/api/Lookup/provinces`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response'
      });
    }

    return this.http.get<TData>(`/api/Lookup/provinces`, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body'
    });
  }
  getApiLookupCities<TData = void>(options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
  getApiLookupCities<TData = void>(options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
  getApiLookupCities<TData = void>(
    options?: HttpClientOptions & { observe: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
  getApiLookupCities<TData = void>(
    options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(`/api/Lookup/cities`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events'
      });
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(`/api/Lookup/cities`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response'
      });
    }

    return this.http.get<TData>(`/api/Lookup/cities`, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body'
    });
  }
  getApiLookupCitiesSearch<TData = void>(
    params?: GetApiLookupCitiesSearchParams,
    options?: HttpClientOptions & { observe?: 'body' }
  ): Observable<TData>;
  getApiLookupCitiesSearch<TData = void>(
    params?: GetApiLookupCitiesSearchParams,
    options?: HttpClientOptions & { observe: 'events' }
  ): Observable<HttpEvent<TData>>;
  getApiLookupCitiesSearch<TData = void>(
    params?: GetApiLookupCitiesSearchParams,
    options?: HttpClientOptions & { observe: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
  getApiLookupCitiesSearch<TData = void>(
    params?: GetApiLookupCitiesSearchParams,
    options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    const filteredParams = filterParams({ ...params, ...options?.params }, new Set<string>([]));

    if (options?.observe === 'events') {
      return this.http.get<TData>(`/api/Lookup/cities/search`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
        params: filteredParams
      });
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(`/api/Lookup/cities/search`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
        params: filteredParams
      });
    }

    return this.http.get<TData>(`/api/Lookup/cities/search`, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body',
      params: filteredParams
    });
  }
  getApiLookupCountryCountryCities<TData = void>(
    country: string,
    options?: HttpClientOptions & { observe?: 'body' }
  ): Observable<TData>;
  getApiLookupCountryCountryCities<TData = void>(
    country: string,
    options?: HttpClientOptions & { observe: 'events' }
  ): Observable<HttpEvent<TData>>;
  getApiLookupCountryCountryCities<TData = void>(
    country: string,
    options?: HttpClientOptions & { observe: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
  getApiLookupCountryCountryCities<TData = void>(
    country: string,
    options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(`/api/Lookup/country/${country}/cities`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events'
      });
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(`/api/Lookup/country/${country}/cities`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response'
      });
    }

    return this.http.get<TData>(`/api/Lookup/country/${country}/cities`, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body'
    });
  }
  getApiLookupCountryCountryIdProvinceProvinceIdCities<TData = void>(
    countryId: string,
    provinceId: string,
    options?: HttpClientOptions & { observe?: 'body' }
  ): Observable<TData>;
  getApiLookupCountryCountryIdProvinceProvinceIdCities<TData = void>(
    countryId: string,
    provinceId: string,
    options?: HttpClientOptions & { observe: 'events' }
  ): Observable<HttpEvent<TData>>;
  getApiLookupCountryCountryIdProvinceProvinceIdCities<TData = void>(
    countryId: string,
    provinceId: string,
    options?: HttpClientOptions & { observe: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
  getApiLookupCountryCountryIdProvinceProvinceIdCities<TData = void>(
    countryId: string,
    provinceId: string,
    options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(`/api/Lookup/country/${countryId}/province/${provinceId}/cities`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events'
      });
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(`/api/Lookup/country/${countryId}/province/${provinceId}/cities`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response'
      });
    }

    return this.http.get<TData>(`/api/Lookup/country/${countryId}/province/${provinceId}/cities`, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body'
    });
  }
  getApiLookupRelationships<TData = void>(options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
  getApiLookupRelationships<TData = void>(
    options?: HttpClientOptions & { observe: 'events' }
  ): Observable<HttpEvent<TData>>;
  getApiLookupRelationships<TData = void>(
    options?: HttpClientOptions & { observe: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
  getApiLookupRelationships<TData = void>(
    options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(`/api/Lookup/relationships`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events'
      });
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(`/api/Lookup/relationships`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response'
      });
    }

    return this.http.get<TData>(`/api/Lookup/relationships`, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body'
    });
  }
  getApiLookupAuthRelationships<TData = void>(options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
  getApiLookupAuthRelationships<TData = void>(
    options?: HttpClientOptions & { observe: 'events' }
  ): Observable<HttpEvent<TData>>;
  getApiLookupAuthRelationships<TData = void>(
    options?: HttpClientOptions & { observe: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
  getApiLookupAuthRelationships<TData = void>(
    options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(`/api/Lookup/auth_relationships`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events'
      });
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(`/api/Lookup/auth_relationships`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response'
      });
    }

    return this.http.get<TData>(`/api/Lookup/auth_relationships`, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body'
    });
  }
  getApiLookupRepresentativeRelationships<TData = void>(
    options?: HttpClientOptions & { observe?: 'body' }
  ): Observable<TData>;
  getApiLookupRepresentativeRelationships<TData = void>(
    options?: HttpClientOptions & { observe: 'events' }
  ): Observable<HttpEvent<TData>>;
  getApiLookupRepresentativeRelationships<TData = void>(
    options?: HttpClientOptions & { observe: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
  getApiLookupRepresentativeRelationships<TData = void>(
    options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(`/api/Lookup/representative_relationships`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events'
      });
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(`/api/Lookup/representative_relationships`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response'
      });
    }

    return this.http.get<TData>(`/api/Lookup/representative_relationships`, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body'
    });
  }
  getApiLookupRestitutionRelationships<TData = void>(
    options?: HttpClientOptions & { observe?: 'body' }
  ): Observable<TData>;
  getApiLookupRestitutionRelationships<TData = void>(
    options?: HttpClientOptions & { observe: 'events' }
  ): Observable<HttpEvent<TData>>;
  getApiLookupRestitutionRelationships<TData = void>(
    options?: HttpClientOptions & { observe: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
  getApiLookupRestitutionRelationships<TData = void>(
    options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(`/api/Lookup/restitution_relationships`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events'
      });
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(`/api/Lookup/restitution_relationships`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response'
      });
    }

    return this.http.get<TData>(`/api/Lookup/restitution_relationships`, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body'
    });
  }
  getApiLookupPoliceDetachments<TData = void>(options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
  getApiLookupPoliceDetachments<TData = void>(
    options?: HttpClientOptions & { observe: 'events' }
  ): Observable<HttpEvent<TData>>;
  getApiLookupPoliceDetachments<TData = void>(
    options?: HttpClientOptions & { observe: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
  getApiLookupPoliceDetachments<TData = void>(
    options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(`/api/Lookup/police_detachments`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events'
      });
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(`/api/Lookup/police_detachments`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response'
      });
    }

    return this.http.get<TData>(`/api/Lookup/police_detachments`, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body'
    });
  }
  getApiLookupCourts<TData = void>(options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
  getApiLookupCourts<TData = void>(options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
  getApiLookupCourts<TData = void>(
    options?: HttpClientOptions & { observe: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
  getApiLookupCourts<TData = void>(
    options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(`/api/Lookup/courts`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events'
      });
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(`/api/Lookup/courts`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response'
      });
    }

    return this.http.get<TData>(`/api/Lookup/courts`, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body'
    });
  }
}
