/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * Restitution API
 * API for the Restitution Application
 * OpenAPI spec version: v1
 */
import type { HttpContext, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';

import { Injectable, inject } from '@angular/core';

import { Observable } from 'rxjs';

import type {
  CityLookupDtoLookupResponseDto,
  CitySearchResponseDto,
  CountryLookupDtoLookupResponseDto,
  GetApiLookupsCitiesSearchParams,
  LookupItemDtoLookupResponseDto,
  PoliceDetachmentLookupDtoLookupResponseDto,
  ProvinceLookupDtoLookupResponseDto,
  RelationshipLookupDtoLookupResponseDto
} from '../../model';

interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?: HttpParams | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: { includeHeaders?: string[] } | boolean;
}

function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: Set<string> = new Set()
): Record<string, string | number | boolean | Array<string | number | boolean>> {
  const filteredParams: Record<string, string | number | boolean | null | Array<string | number | boolean>> = {};
  for (const [key, value] of Object.entries(params)) {
    if (Array.isArray(value)) {
      const filtered = value.filter(
        (item) => item != null && (typeof item === 'string' || typeof item === 'number' || typeof item === 'boolean')
      ) as Array<string | number | boolean>;
      if (filtered.length) {
        filteredParams[key] = filtered;
      }
    } else if (value === null && requiredNullableKeys.has(key)) {
      filteredParams[key] = null;
    } else if (
      value != null &&
      (typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean')
    ) {
      filteredParams[key] = value as string | number | boolean;
    }
  }
  return filteredParams as Record<string, string | number | boolean | Array<string | number | boolean>>;
}

@Injectable({ providedIn: 'root' })
export class LookupsService {
  private readonly http = inject(HttpClient);
  getApiLookupsCountries(accept: 'text/plain', options?: HttpClientOptions): Observable<string>;
  getApiLookupsCountries(
    accept: 'application/json',
    options?: HttpClientOptions
  ): Observable<CountryLookupDtoLookupResponseDto>;
  getApiLookupsCountries(
    accept: 'text/json',
    options?: HttpClientOptions
  ): Observable<CountryLookupDtoLookupResponseDto>;
  getApiLookupsCountries(
    accept?: string,
    options?: HttpClientOptions
  ): Observable<CountryLookupDtoLookupResponseDto | string | Blob>;
  getApiLookupsCountries(
    accept: string = 'text/plain',
    options?: HttpClientOptions
  ): Observable<CountryLookupDtoLookupResponseDto | string | Blob> {
    const headers =
      options?.headers instanceof HttpHeaders
        ? options.headers.set('Accept', accept)
        : { ...(options?.headers ?? {}), Accept: accept };

    if (accept.includes('json') || accept.includes('+json')) {
      return this.http.get<CountryLookupDtoLookupResponseDto>(`/api/lookups/countries`, {
        ...options,
        responseType: 'json',
        headers
      });
    } else if (accept.startsWith('text/') || accept.includes('xml')) {
      return this.http.get(`/api/lookups/countries`, {
        ...options,
        responseType: 'text',
        headers
      }) as Observable<string>;
    } else {
      return this.http.get(`/api/lookups/countries`, {
        ...options,
        responseType: 'blob',
        headers
      }) as Observable<Blob>;
    }
  }
  getApiLookupsProvinces(accept: 'text/plain', options?: HttpClientOptions): Observable<string>;
  getApiLookupsProvinces(
    accept: 'application/json',
    options?: HttpClientOptions
  ): Observable<ProvinceLookupDtoLookupResponseDto>;
  getApiLookupsProvinces(
    accept: 'text/json',
    options?: HttpClientOptions
  ): Observable<ProvinceLookupDtoLookupResponseDto>;
  getApiLookupsProvinces(
    accept?: string,
    options?: HttpClientOptions
  ): Observable<ProvinceLookupDtoLookupResponseDto | string | Blob>;
  getApiLookupsProvinces(
    accept: string = 'text/plain',
    options?: HttpClientOptions
  ): Observable<ProvinceLookupDtoLookupResponseDto | string | Blob> {
    const headers =
      options?.headers instanceof HttpHeaders
        ? options.headers.set('Accept', accept)
        : { ...(options?.headers ?? {}), Accept: accept };

    if (accept.includes('json') || accept.includes('+json')) {
      return this.http.get<ProvinceLookupDtoLookupResponseDto>(`/api/lookups/provinces`, {
        ...options,
        responseType: 'json',
        headers
      });
    } else if (accept.startsWith('text/') || accept.includes('xml')) {
      return this.http.get(`/api/lookups/provinces`, {
        ...options,
        responseType: 'text',
        headers
      }) as Observable<string>;
    } else {
      return this.http.get(`/api/lookups/provinces`, {
        ...options,
        responseType: 'blob',
        headers
      }) as Observable<Blob>;
    }
  }
  getApiLookupsCities(accept: 'text/plain', options?: HttpClientOptions): Observable<string>;
  getApiLookupsCities(
    accept: 'application/json',
    options?: HttpClientOptions
  ): Observable<CityLookupDtoLookupResponseDto>;
  getApiLookupsCities(accept: 'text/json', options?: HttpClientOptions): Observable<CityLookupDtoLookupResponseDto>;
  getApiLookupsCities(
    accept?: string,
    options?: HttpClientOptions
  ): Observable<CityLookupDtoLookupResponseDto | string | Blob>;
  getApiLookupsCities(
    accept: string = 'text/plain',
    options?: HttpClientOptions
  ): Observable<CityLookupDtoLookupResponseDto | string | Blob> {
    const headers =
      options?.headers instanceof HttpHeaders
        ? options.headers.set('Accept', accept)
        : { ...(options?.headers ?? {}), Accept: accept };

    if (accept.includes('json') || accept.includes('+json')) {
      return this.http.get<CityLookupDtoLookupResponseDto>(`/api/lookups/cities`, {
        ...options,
        responseType: 'json',
        headers
      });
    } else if (accept.startsWith('text/') || accept.includes('xml')) {
      return this.http.get(`/api/lookups/cities`, {
        ...options,
        responseType: 'text',
        headers
      }) as Observable<string>;
    } else {
      return this.http.get(`/api/lookups/cities`, {
        ...options,
        responseType: 'blob',
        headers
      }) as Observable<Blob>;
    }
  }
  getApiLookupsCitiesSearch(
    accept: 'text/plain',
    params?: GetApiLookupsCitiesSearchParams,
    options?: HttpClientOptions
  ): Observable<string>;
  getApiLookupsCitiesSearch(
    accept: 'application/json',
    params?: GetApiLookupsCitiesSearchParams,
    options?: HttpClientOptions
  ): Observable<CitySearchResponseDto>;
  getApiLookupsCitiesSearch(
    accept: 'text/json',
    params?: GetApiLookupsCitiesSearchParams,
    options?: HttpClientOptions
  ): Observable<CitySearchResponseDto>;
  getApiLookupsCitiesSearch(
    accept?: string,
    params?: GetApiLookupsCitiesSearchParams,
    options?: HttpClientOptions
  ): Observable<CitySearchResponseDto | string | Blob>;
  getApiLookupsCitiesSearch(
    accept: string = 'text/plain',
    params?: GetApiLookupsCitiesSearchParams,
    options?: HttpClientOptions
  ): Observable<CitySearchResponseDto | string | Blob> {
    const queryParams = params != null ? filterParams(params as Record<string, unknown>) : options?.params;

    const headers =
      options?.headers instanceof HttpHeaders
        ? options.headers.set('Accept', accept)
        : { ...(options?.headers ?? {}), Accept: accept };

    if (accept.includes('json') || accept.includes('+json')) {
      return this.http.get<CitySearchResponseDto>(`/api/lookups/cities/search`, {
        ...options,
        params: queryParams,
        responseType: 'json',
        headers
      });
    } else if (accept.startsWith('text/') || accept.includes('xml')) {
      return this.http.get(`/api/lookups/cities/search`, {
        ...options,
        params: queryParams,
        responseType: 'text',
        headers
      }) as Observable<string>;
    } else {
      return this.http.get(`/api/lookups/cities/search`, {
        ...options,
        params: queryParams,
        responseType: 'blob',
        headers
      }) as Observable<Blob>;
    }
  }
  getApiLookupsCountryCountryCities(
    country: string,
    accept: 'text/plain',
    options?: HttpClientOptions
  ): Observable<string>;
  getApiLookupsCountryCountryCities(
    country: string,
    accept: 'application/json',
    options?: HttpClientOptions
  ): Observable<CityLookupDtoLookupResponseDto>;
  getApiLookupsCountryCountryCities(
    country: string,
    accept: 'text/json',
    options?: HttpClientOptions
  ): Observable<CityLookupDtoLookupResponseDto>;
  getApiLookupsCountryCountryCities(
    country: string,
    accept?: string,
    options?: HttpClientOptions
  ): Observable<CityLookupDtoLookupResponseDto | string | Blob>;
  getApiLookupsCountryCountryCities(
    country: string,
    accept: string = 'text/plain',
    options?: HttpClientOptions
  ): Observable<CityLookupDtoLookupResponseDto | string | Blob> {
    const headers =
      options?.headers instanceof HttpHeaders
        ? options.headers.set('Accept', accept)
        : { ...(options?.headers ?? {}), Accept: accept };

    if (accept.includes('json') || accept.includes('+json')) {
      return this.http.get<CityLookupDtoLookupResponseDto>(`/api/lookups/country/${country}/cities`, {
        ...options,
        responseType: 'json',
        headers
      });
    } else if (accept.startsWith('text/') || accept.includes('xml')) {
      return this.http.get(`/api/lookups/country/${country}/cities`, {
        ...options,
        responseType: 'text',
        headers
      }) as Observable<string>;
    } else {
      return this.http.get(`/api/lookups/country/${country}/cities`, {
        ...options,
        responseType: 'blob',
        headers
      }) as Observable<Blob>;
    }
  }
  getApiLookupsCountryCountryIdProvinceProvinceIdCities(
    countryId: string,
    provinceId: string,
    accept: 'text/plain',
    options?: HttpClientOptions
  ): Observable<string>;
  getApiLookupsCountryCountryIdProvinceProvinceIdCities(
    countryId: string,
    provinceId: string,
    accept: 'application/json',
    options?: HttpClientOptions
  ): Observable<CityLookupDtoLookupResponseDto>;
  getApiLookupsCountryCountryIdProvinceProvinceIdCities(
    countryId: string,
    provinceId: string,
    accept: 'text/json',
    options?: HttpClientOptions
  ): Observable<CityLookupDtoLookupResponseDto>;
  getApiLookupsCountryCountryIdProvinceProvinceIdCities(
    countryId: string,
    provinceId: string,
    accept?: string,
    options?: HttpClientOptions
  ): Observable<CityLookupDtoLookupResponseDto | string | Blob>;
  getApiLookupsCountryCountryIdProvinceProvinceIdCities(
    countryId: string,
    provinceId: string,
    accept: string = 'text/plain',
    options?: HttpClientOptions
  ): Observable<CityLookupDtoLookupResponseDto | string | Blob> {
    const headers =
      options?.headers instanceof HttpHeaders
        ? options.headers.set('Accept', accept)
        : { ...(options?.headers ?? {}), Accept: accept };

    if (accept.includes('json') || accept.includes('+json')) {
      return this.http.get<CityLookupDtoLookupResponseDto>(
        `/api/lookups/country/${countryId}/province/${provinceId}/cities`,
        {
          ...options,
          responseType: 'json',
          headers
        }
      );
    } else if (accept.startsWith('text/') || accept.includes('xml')) {
      return this.http.get(`/api/lookups/country/${countryId}/province/${provinceId}/cities`, {
        ...options,
        responseType: 'text',
        headers
      }) as Observable<string>;
    } else {
      return this.http.get(`/api/lookups/country/${countryId}/province/${provinceId}/cities`, {
        ...options,
        responseType: 'blob',
        headers
      }) as Observable<Blob>;
    }
  }
  getApiLookupsRelationships(accept: 'text/plain', options?: HttpClientOptions): Observable<string>;
  getApiLookupsRelationships(
    accept: 'application/json',
    options?: HttpClientOptions
  ): Observable<RelationshipLookupDtoLookupResponseDto>;
  getApiLookupsRelationships(
    accept: 'text/json',
    options?: HttpClientOptions
  ): Observable<RelationshipLookupDtoLookupResponseDto>;
  getApiLookupsRelationships(
    accept?: string,
    options?: HttpClientOptions
  ): Observable<RelationshipLookupDtoLookupResponseDto | string | Blob>;
  getApiLookupsRelationships(
    accept: string = 'text/plain',
    options?: HttpClientOptions
  ): Observable<RelationshipLookupDtoLookupResponseDto | string | Blob> {
    const headers =
      options?.headers instanceof HttpHeaders
        ? options.headers.set('Accept', accept)
        : { ...(options?.headers ?? {}), Accept: accept };

    if (accept.includes('json') || accept.includes('+json')) {
      return this.http.get<RelationshipLookupDtoLookupResponseDto>(`/api/lookups/relationships`, {
        ...options,
        responseType: 'json',
        headers
      });
    } else if (accept.startsWith('text/') || accept.includes('xml')) {
      return this.http.get(`/api/lookups/relationships`, {
        ...options,
        responseType: 'text',
        headers
      }) as Observable<string>;
    } else {
      return this.http.get(`/api/lookups/relationships`, {
        ...options,
        responseType: 'blob',
        headers
      }) as Observable<Blob>;
    }
  }
  getApiLookupsAuthRelationships(accept: 'text/plain', options?: HttpClientOptions): Observable<string>;
  getApiLookupsAuthRelationships(
    accept: 'application/json',
    options?: HttpClientOptions
  ): Observable<RelationshipLookupDtoLookupResponseDto>;
  getApiLookupsAuthRelationships(
    accept: 'text/json',
    options?: HttpClientOptions
  ): Observable<RelationshipLookupDtoLookupResponseDto>;
  getApiLookupsAuthRelationships(
    accept?: string,
    options?: HttpClientOptions
  ): Observable<RelationshipLookupDtoLookupResponseDto | string | Blob>;
  getApiLookupsAuthRelationships(
    accept: string = 'text/plain',
    options?: HttpClientOptions
  ): Observable<RelationshipLookupDtoLookupResponseDto | string | Blob> {
    const headers =
      options?.headers instanceof HttpHeaders
        ? options.headers.set('Accept', accept)
        : { ...(options?.headers ?? {}), Accept: accept };

    if (accept.includes('json') || accept.includes('+json')) {
      return this.http.get<RelationshipLookupDtoLookupResponseDto>(`/api/lookups/auth_relationships`, {
        ...options,
        responseType: 'json',
        headers
      });
    } else if (accept.startsWith('text/') || accept.includes('xml')) {
      return this.http.get(`/api/lookups/auth_relationships`, {
        ...options,
        responseType: 'text',
        headers
      }) as Observable<string>;
    } else {
      return this.http.get(`/api/lookups/auth_relationships`, {
        ...options,
        responseType: 'blob',
        headers
      }) as Observable<Blob>;
    }
  }
  getApiLookupsRepresentativeRelationships(accept: 'text/plain', options?: HttpClientOptions): Observable<string>;
  getApiLookupsRepresentativeRelationships(
    accept: 'application/json',
    options?: HttpClientOptions
  ): Observable<RelationshipLookupDtoLookupResponseDto>;
  getApiLookupsRepresentativeRelationships(
    accept: 'text/json',
    options?: HttpClientOptions
  ): Observable<RelationshipLookupDtoLookupResponseDto>;
  getApiLookupsRepresentativeRelationships(
    accept?: string,
    options?: HttpClientOptions
  ): Observable<RelationshipLookupDtoLookupResponseDto | string | Blob>;
  getApiLookupsRepresentativeRelationships(
    accept: string = 'text/plain',
    options?: HttpClientOptions
  ): Observable<RelationshipLookupDtoLookupResponseDto | string | Blob> {
    const headers =
      options?.headers instanceof HttpHeaders
        ? options.headers.set('Accept', accept)
        : { ...(options?.headers ?? {}), Accept: accept };

    if (accept.includes('json') || accept.includes('+json')) {
      return this.http.get<RelationshipLookupDtoLookupResponseDto>(`/api/lookups/representative_relationships`, {
        ...options,
        responseType: 'json',
        headers
      });
    } else if (accept.startsWith('text/') || accept.includes('xml')) {
      return this.http.get(`/api/lookups/representative_relationships`, {
        ...options,
        responseType: 'text',
        headers
      }) as Observable<string>;
    } else {
      return this.http.get(`/api/lookups/representative_relationships`, {
        ...options,
        responseType: 'blob',
        headers
      }) as Observable<Blob>;
    }
  }
  getApiLookupsRestitutionRelationships(accept: 'text/plain', options?: HttpClientOptions): Observable<string>;
  getApiLookupsRestitutionRelationships(
    accept: 'application/json',
    options?: HttpClientOptions
  ): Observable<RelationshipLookupDtoLookupResponseDto>;
  getApiLookupsRestitutionRelationships(
    accept: 'text/json',
    options?: HttpClientOptions
  ): Observable<RelationshipLookupDtoLookupResponseDto>;
  getApiLookupsRestitutionRelationships(
    accept?: string,
    options?: HttpClientOptions
  ): Observable<RelationshipLookupDtoLookupResponseDto | string | Blob>;
  getApiLookupsRestitutionRelationships(
    accept: string = 'text/plain',
    options?: HttpClientOptions
  ): Observable<RelationshipLookupDtoLookupResponseDto | string | Blob> {
    const headers =
      options?.headers instanceof HttpHeaders
        ? options.headers.set('Accept', accept)
        : { ...(options?.headers ?? {}), Accept: accept };

    if (accept.includes('json') || accept.includes('+json')) {
      return this.http.get<RelationshipLookupDtoLookupResponseDto>(`/api/lookups/restitution_relationships`, {
        ...options,
        responseType: 'json',
        headers
      });
    } else if (accept.startsWith('text/') || accept.includes('xml')) {
      return this.http.get(`/api/lookups/restitution_relationships`, {
        ...options,
        responseType: 'text',
        headers
      }) as Observable<string>;
    } else {
      return this.http.get(`/api/lookups/restitution_relationships`, {
        ...options,
        responseType: 'blob',
        headers
      }) as Observable<Blob>;
    }
  }
  getApiLookupsPoliceDetachments(accept: 'text/plain', options?: HttpClientOptions): Observable<string>;
  getApiLookupsPoliceDetachments(
    accept: 'application/json',
    options?: HttpClientOptions
  ): Observable<PoliceDetachmentLookupDtoLookupResponseDto>;
  getApiLookupsPoliceDetachments(
    accept: 'text/json',
    options?: HttpClientOptions
  ): Observable<PoliceDetachmentLookupDtoLookupResponseDto>;
  getApiLookupsPoliceDetachments(
    accept?: string,
    options?: HttpClientOptions
  ): Observable<PoliceDetachmentLookupDtoLookupResponseDto | string | Blob>;
  getApiLookupsPoliceDetachments(
    accept: string = 'text/plain',
    options?: HttpClientOptions
  ): Observable<PoliceDetachmentLookupDtoLookupResponseDto | string | Blob> {
    const headers =
      options?.headers instanceof HttpHeaders
        ? options.headers.set('Accept', accept)
        : { ...(options?.headers ?? {}), Accept: accept };

    if (accept.includes('json') || accept.includes('+json')) {
      return this.http.get<PoliceDetachmentLookupDtoLookupResponseDto>(`/api/lookups/police_detachments`, {
        ...options,
        responseType: 'json',
        headers
      });
    } else if (accept.startsWith('text/') || accept.includes('xml')) {
      return this.http.get(`/api/lookups/police_detachments`, {
        ...options,
        responseType: 'text',
        headers
      }) as Observable<string>;
    } else {
      return this.http.get(`/api/lookups/police_detachments`, {
        ...options,
        responseType: 'blob',
        headers
      }) as Observable<Blob>;
    }
  }
  getApiLookupsCourts(accept: 'text/plain', options?: HttpClientOptions): Observable<string>;
  getApiLookupsCourts(
    accept: 'application/json',
    options?: HttpClientOptions
  ): Observable<LookupItemDtoLookupResponseDto>;
  getApiLookupsCourts(accept: 'text/json', options?: HttpClientOptions): Observable<LookupItemDtoLookupResponseDto>;
  getApiLookupsCourts(
    accept?: string,
    options?: HttpClientOptions
  ): Observable<LookupItemDtoLookupResponseDto | string | Blob>;
  getApiLookupsCourts(
    accept: string = 'text/plain',
    options?: HttpClientOptions
  ): Observable<LookupItemDtoLookupResponseDto | string | Blob> {
    const headers =
      options?.headers instanceof HttpHeaders
        ? options.headers.set('Accept', accept)
        : { ...(options?.headers ?? {}), Accept: accept };

    if (accept.includes('json') || accept.includes('+json')) {
      return this.http.get<LookupItemDtoLookupResponseDto>(`/api/lookups/courts`, {
        ...options,
        responseType: 'json',
        headers
      });
    } else if (accept.startsWith('text/') || accept.includes('xml')) {
      return this.http.get(`/api/lookups/courts`, {
        ...options,
        responseType: 'text',
        headers
      }) as Observable<string>;
    } else {
      return this.http.get(`/api/lookups/courts`, {
        ...options,
        responseType: 'blob',
        headers
      }) as Observable<Blob>;
    }
  }
}
