name: cd-restitution-api

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/workflows/cd-restitution-ui.yml'
      - 'restitution-app/ClientApp/**'
      - 'COMPLIANCE.yaml'
      - 'LICENSE'
      - 'README.md'

env:
  APP_NAME: restitution
  BUILD_ID: ${{ github.server_url }}!${{ github.repository }}!${{ github.ref_name }}!${{ github.sha }}!${{ github.run_number }}
  IMAGE_REGISTRY: ${{ secrets.OCP4_REGISTRY }}/${{ secrets.OCP4_NAMESPACE }}

jobs:
  build-restitution-api:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'bcgov'
    env:
      IMAGE_NAME: api
      RESTITUTION_API_DOCKERFILE_PATH: ./restitution-app/Dockerfile

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx tooling
        uses: docker/setup-buildx-action@v3

      - name: Log into OpenShift Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ secrets.OCP4_USERNAME }}
          password: ${{ secrets.OCP4_PASSWORD }}

      - name: Pull image
        run: docker pull ${{ env.IMAGE_REGISTRY }}/${{ env.APP_NAME }}-${{ env.IMAGE_NAME }}:dev || true

      - name: Bump version
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ${{ env.APP_NAME }}-${{ env.IMAGE_NAME }}=v
          fetch_all_tags: true


      - name: Create version env var
        run: echo "BUILD_VERSION=$(echo '${{ steps.tag_version.outputs.new_tag }}' | awk -F-v '{print $NF}')" >> $GITHUB_ENV


      - name: Build and push restitution-app-api
        uses: docker/build-push-action@v6
        with:
          build-args: |
            BUILD_ID="${{ env.BUILD_ID }}"
            BUILD_VERSION=${{ env.BUILD_VERSION }}
          cache-from: |
            ${{ env.IMAGE_REGISTRY }}/${{ env.APP_NAME }}-${{ env.IMAGE_NAME }}
          file: ${{ env.RESTITUTION_API_DOCKERFILE_PATH }}
          push: true
          tags: |
            ${{ env.IMAGE_REGISTRY }}/${{ env.APP_NAME }}-${{ env.IMAGE_NAME }}:dev

      - name: Save image as tarball for Trivy
        run: |
          docker save "$IMAGE_REGISTRY/$APP_NAME-$IMAGE_NAME:dev" -o "$APP_NAME-$IMAGE_NAME.tar"

      - name: Install Trivy
        run: |
          wget -qO- https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | bash
          echo "$(pwd)/bin" >> $GITHUB_PATH

      - name: Trivy scan for restitution api image
        continue-on-error: true
        run: |
          trivy image restitution-api.tar \
            --severity HIGH,CRITICAL \
            --ignore-unfixed \
            --exit-code 1 \
            --format sarif \
            --output trivy-restitution-api-image-scan.sarif

      - name: Upload scan results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-restitution-api-image-scan.sarif
          category: trivy-built-image-scan-results